#!/bin/bash
export NXF_SINGULARITY_CACHEDIR=/dev/shm/oyedele/
export SINGULARITY_TMPDIR=/dev/shm/oyedele/


nextflow run nf-core/differentialabundance \
 -profile rnaseq,singularity \
 --outdir path to output \
 --input path to csv file (nf-core_script_F_vs_R \
 --contrasts path to contrast contrasts.csv \
 --matrix path to /star_salmon/salmon.merged.gene_counts.tsv \
 --transcript_length_matrix path to /star_salmon/salmon.merged.gene_lengths.tsv \
 --gtf path to fasta file /mapping_files/Homo_sapiens.GRCh38.111.gtf.gz \
 -w working directory \
