#!/bin/bash
export NXF_SINGULARITY_CACHEDIR=/mnt/projects/users/oyedele
export SINGULARITY_TMPDIR=/mnt/projects/users/oyedele

nextflow run nf-core/rnaseq \
    -profile singularity \
    --input path to csv file (nf-core_script_F_vs_R) \
    --outdir path to output folder \
    --gtf path to reference genome/mapping_files/Homo_sapiens.GRCh38.111.gtf.gz \
    --fasta path to fasta file /mapping_files/Homo_sapiens.GRCh38.dna_sm.primary_assembly.fa.gz \
    --igenomes_ignore \
    --genome null \
    -w work directory
