#!/bin/bash
export NXF_SINGULARITY_CACHEDIR=/mnt/projects/users/oyedele
export SINGULARITY_TMPDIR=/mnt/projects/users/oyedele

#nextflow run nf-core/rnaseq \
# -profile test,singularity \
#  --outdir /home/oola249/test_rnaseq \
# -w /dev/shm/rnaseq_work \
#  -resume


nextflow run nf-core/rnaseq \
    -profile singularity \
    --input /home/oola249/T2_4x4_Reversal.csv \
    --outdir /mnt/projects/users/oyedele/rnaseq_T2_4x4_Reversal_Batch \
    --gtf /home/oola249/projects/mapping_files/Homo_sapiens.GRCh38.111.gtf.gz \
    --fasta /home/oola249/projects/mapping_files/Homo_sapiens.GRCh38.dna_sm.primary_assembly.fa.gz \
    --igenomes_ignore \
    --genome null \
    -w /mnt/projects/users/oyedele/T2_4x4_Reversal_rnaseq_result
